### ISSUE TITLE
Find solution / add csrf filter again

### ISSUE THREAD

**Issue by johnzielke** [SwaggerTagger/octo-tagger-backend#1]
Currently the csrf filter is configured to be bypassable. To deactivate remove play.filters.csrf.header.bypassHeaders {
  X-Requested-With = "*"
  Csrf-Token = "nocheck"
}
from configuration

**Comment by georggrab** [comment]
is this still relevant? regarding our design choice to serve both frontend and backend from the same server but different endponts

**Comment by johnzielke** [comment]
lets close this for now
