### ISSUE TITLE
Activation email with wrong hostname

### ISSUE THREAD

**Issue by johnzielke** [SwaggerTagger/octo-tagger-backend#12]
Activation emails sent through kafka have wrong hostname
Steps to reproduce:
1. Register at [gruppe7.testsites.info](gruppe7.testsites.info)
2. Click on link in email

**Comment by georggrab** [comment]
fixed.

**Comment by johnzielke** [comment]
Wow, that was quick:DD

talkdirty <notifications@github.com> schrieb am Mi., 17. Mai 2017, 23:53:
